### ISSUE TITLE
Manually scheduling should be set to True on task when project is autoscheduled

### ISSUE THREAD

**Issue by javascript-programming** [bryntum/odoo-support#117]
https://forum.bryntum.com/viewtopic.php?t=25570

**Comment by mnoukrati** [comment]
Hello Terence
This issue was reported on Odoo v15 community edition
This happens even if we activate "Manually scheduled"
is it possible to correct this ASAP, we have the issue in a production database

**Comment by javascript-programming** [comment]
This issue is scheduled for the upcoming release. Not sure if it s related to your case. 
When the project is not auto scheduled then Manually Scheduled will be always set to True.

**Comment by kiferrara** [comment]
Hi
Has this issue been fixed in 2.0.5? We upgraded the module on our environment but it still doesn't work

**Comment by javascript-programming** [comment]
In 2.0.6. And make sure that the project is not set to auto scheduled in global settings or project settings.
