### ISSUE TITLE
Odoo 14 version cannot be installed

### ISSUE THREAD

**Issue by DaniRey** [bryntum/odoo-support#127]
I tried to install Version 2.1.1 on Odoo community 14 and failed due to mismatching field names (user_ids instead of user_id) in project_view.xml. Also the Gantt Pro was not loaded at all, because `views/templates.xml` was commented in the manifest.

Can you release a working version of Gantt Pro for Odoo community 14? It seems to be only tested on newer Odoo versions.

I attached a [bryntum_gantt_odoo14.patch](https://github.com/bryntum/odoo-support/files/12828486/bryntum_gantt_odoo14.patch) with the fixes I had to make to get it running. Unfortunately it is hard to tell if these are complete - as I am not yet aware of all features of Gantt Pro.

**Comment by sufyanel** [comment]
Hi Dani we are working on these issues and update the code as soon as possible.

**Comment by sufyanel** [comment]
odoo 14 has been updated now you can install that.

**Comment by thomich** [comment]
we are also have issus with 2.1.1, solved them based on above description, but still issues, see details on https://forum.bryntum.com/viewtopic.php?t=26585

**Comment by thomaspaulb** [comment]
Was solved.
