### ISSUE TITLE
[FIX] wrong user_ids field reference in 13.0 project views

### ISSUE THREAD

**Issue by gjotten** [bryntum/odoo-support#130]
Among other places throughout the latest commit, in [13.0 views](https://github.com/bryntum/odoo-app/blob/13.0/bryntum_gantt/views/project_views.xml) we see `user_ids` referenced as a field even though this was introduced only in 15.0+

Original forum post [here](https://forum.bryntum.com/viewtopic.php?t=28325)

**Comment by gjotten** [comment]
@gfcapalbo I think fixing this is low-hanging fruit which can be initiated very soon.

**Comment by gfcapalbo** [comment]
solved and installed on v13 instances

**Comment by gjotten** [comment]
> solved and installed on v13 instances

We don't need to link to our private repo on a public one; in these cases please tag from the MR :slightly_smiling_face:
