### ISSUE TITLE
Show multiple projects in the gantt chart

### ISSUE THREAD

**Issue by javascript-programming** [bryntum/odoo-support#2]
Currently we show only one selected project in the gantt view. 

Feature request to show multiple projects

- Add select option for projects
- Show option or button to launch chart

Or launch the view as currently is done and have an internal gantt option to show other projects next to the current shown/selected project. 

In that case the controller should have an entry to retrieve all available projects

**Comment by christos-ts** [comment]
Great. Many thanks.

**Comment by christos-ts** [comment]
Hello!
Any news on this extremely useful feature?

**Comment by javascript-programming** [comment]
Not yet. The gantt view is now part of a project navigation route in Odoo. In what way do you wish to select multiple projects?

**Comment by christos-ts** [comment]
hello, thank you for your prompt reply.
We are evaluating the odoo gantt and we propose the following:
Add the "gantt view" button on tasks view . Then user will be able to filter tasks from kanban or in line view based on project and then depict those in bryntum-gantt view.  
hope that this is possible!
![Screenshot 2021-05-30 124808](https://user-images.githubusercontent.com/84321923/120099741-decfda00-c145-11eb-95f7-dfe442bdc4fe.jpg)

**Comment by christos-ts** [comment]
Hello! Any feedback on this ?
Much Appreciated,
Christos

**Comment by javascript-programming** [comment]
This is still under investigation. It requires some refactoring to show and select more projects in the chart.

**Comment by codeagencybe** [comment]
Any update on this? Or an ETA when this will be expected? 
I'm very much interested buying this Gantt module, but without this feature its totally useless. 
If I can't have a global overview of all project tasks at same time, there is no point in using a Gantt view for companies dealing with multiple projects running at same time. 

Thanks!

**Comment by javascript-programming** [comment]
No, no ETA yet, But I discuss this upcoming Monday. We are still looking for the best flow to select multiple projects. If any additional suggestions please let us know.

**Comment by javascript-programming** [comment]
We do not have the ability found to show multiple project at in the same view. Still investigating.

**Comment by christos-ts** [comment]
This is a very important feature for many firms that want to use the module to actively manage projects.
Hope this can be found and implemented soon.
Looking forward for any updates.
Thank you

**Comment by codeagencybe** [comment]
@christos-ts 
There are a few other apps in the appstore that do support the multi-project Gantt view. 
There is one from Ksolves and one from Codefort that support this.  
I didn't compare other features (less import imho) but for my company this problem is also a showstopper and had to deviate to other solutions. 
It's impossible to manage an agency with multiple parallel projects if you can't have a global overview of everything.

**Comment by javascript-programming** [comment]
Thank you for your point out to those apps.  We will put multi-projects higher on our list.

**Comment by SFN1** [comment]
Hi, 
Is there any update or ETA on this? 
Thanks

**Comment by javascript-programming** [comment]
Not yet still working on it

**Comment by WassilyPrioticket** [comment]
> Not yet still working on it

Hi dear programmer,

Our company Odoo roll-out is depending on this functionality now.

Do you have an ETA on this? It would help us with making a proper planning.

Thank you in advance.

**Comment by javascript-programming** [comment]
Hi, currently this ticket is in progress we hope to deliver within two weeks.

**Comment by WassilyPrioticket** [comment]
Hi, 

That is amazing news!

In which way will we and other users be informed about this?

**Comment by javascript-programming** [comment]
You will see this issue closed. And we will add a changelog in the module description which you can view in odoo's app store. 

Maybe we should open a forum thread with the changelog too.

**Comment by SFN1** [comment]
great news - looking forward to it

**Comment by WassilyPrioticket** [comment]
Hi programmer,

I was wondering if you have an update for us regarding the above, now we are two weeks down the line.

Looking forward to you reply.

**Comment by javascript-programming** [comment]
In progress. 1 or 2 weeks I guess

**Comment by WassilyPrioticket** [comment]
That was said two weeks ago as well. The move of our entire company is dependant on this. 

Can you please provide a realistic delivery date so we can plan?

**Comment by javascript-programming** [comment]
It is now currently under development or in progress. Like mentioned above.

**Comment by flyeee** [comment]
We are looking for this feature as well, is this feature done, or will release recently? @javascript-programming

**Comment by javascript-programming** [comment]
Currently under development. It will look like this. You pick an initial project in the chart there will be a dropdown to select other projects by side. 


![Screenshot 2021-10-15 at 19 25 29](https://user-images.githubusercontent.com/25703411/137528707-fa60188b-ff2c-4c67-a706-b1e93df6fe42.png)

ETA upcoming week hopefully

**Comment by flyeee** [comment]
Great, could you make sure there is an option to select all the projects at one time?

**Comment by WassilyPrioticket** [comment]
Yes, the "all" option would be a crucial functionality to have indeed.

**Comment by flyeee** [comment]
Hello, is it gonna be coming this week?

**Comment by javascript-programming** [comment]
It is there! First release. 

https://odoo-gantt.bryntum.com

It does not have a select all option at the moment. But that could be added.

**Comment by flyeee** [comment]
Great, when can I get this version from the odoo store?

**Comment by javascript-programming** [comment]
If correct it is there now. But I discovered some sources did not upload correctly to the Store. Asked my colleague to rescan the Odoo repo's again. To be sure try tomorrow. It is in version 1.2.7

**Comment by SFN1** [comment]
great - thanks alot
