### ISSUE TITLE
 Duplicate project with its subtasks, dependencies and segments  

### ISSUE THREAD

**Issue by javascript-programming** [bryntum/odoo-support#23]
with all dependencies and assignments

https://www.bryntum.com/forum/viewtopic.php?f=58&t=18377

**Comment by DamienOGE** [comment]
This feature can also be applied with copy and pasting inside a project. Currently copy-pasted items reference the original dependencies, instead of being independant.

**Comment by DamienOGE** [comment]
@javascript-programming We have implemented a version of this feature if you are interested in the code.

**Comment by javascript-programming** [comment]
Nice! I would like to have the view of multiple projects in place first. From there we have a good starting point to copy. I saw there are functions in the model to clone or copy. 

But very interested in ways how we can improve. If you think it can benefit the use of the gantt view. We could adopt idea's or proposed pieces of code. Maybe have a screenshare / meeting on short term?

**Comment by javascript-programming** [comment]
Use the native duplicate action instead. Action should be extended to copy dependencies/assignments/baseline. Basically all fields that are extended from the project model.

**Comment by javascript-programming** [comment]
Resolved by extending the duplicate action. 
- will copy dependencies and segments

Assignments and baselines will not be copied, in this way the copy action can be used for template projects without.
