### ISSUE TITLE
Only users are selectable as resources

### ISSUE THREAD

**Issue by DamienOGE** [bryntum/odoo-support#38]
The resources field only provides users, from res.users, as assignable resources. If this is the desired behaviour it limits the scope available, as every person being scheduled would need to have an active account with the associated costs.  This also prevents the scheduling of machine time without getting creative with user objects.
Consider using Resources (resource.resource) instead of or in addition to res.users, so Employee and Material objects can be used.

**Comment by DamienOGE** [comment]
Appears to be resolved in version 14.0.1.2.4. I am yet to check with the stock module; I will confirm and close the issue if it is the case.

**Comment by javascript-programming** [comment]
Yes we are loading the resources as well. Please let us know if it can be improved. Both users and and resources are returned. 
This is done for backward compatibility and adjusted when we have project configuration in place.

**Comment by DamienOGE** [comment]
Works as described and issue closed. 
Note regarding the current implementation:
1. Existing projects with users allocated will not show resources, it must be a new project
2. When a user exists and is attached to an employee, both the user and the employee are selectable. When both have the same name, it is not clear which is correct. Workarounds are renaming one item, or in the future potentially Bryntum Gantt adding a tag on the returned names.

**Comment by javascript-programming** [comment]
1. Yes we store the assignments differently but we could however copy those. When we attach resource allocation we are probably going to follow that path. 
2. That is indeed the case. For backward compatibility reasons. We are going to make the resource source configurable in the near future.
