### ISSUE TITLE
Date format not selectable and not using localization information

### ISSUE THREAD

**Issue by DamienOGE** [bryntum/odoo-support#43]
Currently the date format is showing the US style MM/DD/YYYY . 
Our company location is set to Germany, which has style DD.MM.YYYY .
Language is set to English (UK), which has style DD/MM/YYYY .
Not currently a showstopper, but it would be good to have the option to change it or hard code it. Better would be to have it look up either the company or language location with the option of an override.

**Comment by javascript-programming** [comment]
Agree this should be added on the short term.
