### ISSUE TITLE
Setting a start date out of range will result in an error and crash

### ISSUE THREAD

**Issue by DamienOGE** [bryntum/odoo-support#46]
Changing the date to one out of range, such as one in the year 20211, will result in a crash. This occurs occasionally when users are manually inputting dates and make an error.
In these cases expected behaviour would be rejection of the input, setting the date at the maximum possible date, or an error state that doesn't require a refresh to exit.

**Comment by javascript-programming** [comment]
Where does this happen, in the Odoo form

**Comment by DamienOGE** [comment]
I have attached two images showing the areas that I was inputting the date.
![Screenshot 2021-10-07 144814](https://user-images.githubusercontent.com/79400658/136388290-e43a6010-be27-4905-89b4-f1249cb1a9f6.jpg)
![Screenshot 2021-10-07 144738](https://user-images.githubusercontent.com/79400658/136388294-0c88336a-6b96-4b72-956f-92f98d571d8e.jpg)

**Comment by javascript-programming** [comment]
Confirmed! Thank you for the report.
