### ISSUE TITLE
Dynamically add task model fields to be returned for the Gantt View 

### ISSUE THREAD

**Issue by javascript-programming** [bryntum/odoo-support#47]
- should recognise model fields in de task model
- return the newly added field values in json

- map fields to Gantt Column (already possible)

**Comment by patriciopa** [comment]
Hi !
How do you map fields to Gantt Column ?

**Comment by javascript-programming** [comment]
https://www.bryntum.com/forum/viewtopic.php?f=58&t=21932

Add the fields to js model
