### ISSUE TITLE
Data synchronization native task model

### ISSUE THREAD

**Issue by javascript-programming** [bryntum/odoo-support#48]
We currently use dedicated fields in the task model for the gantt view

Like

- effort
- assignments

Investigate how and if they can be synchronized

**Comment by xiaoguai1818** [comment]
At present, we need Gantt view to assist in the management of tasks in the project. Executives need to view their own tasks in the odoo native interface, so they need to synchronize the odoo native fields

**Comment by javascript-programming** [comment]
https://www.bryntum.com/forum/viewtopic.php?f=58&t=20048&p=99431#p99431

planned_hours
effective_hours
remaining_hours
tag_ids
