### ISSUE TITLE
Tasks in folded Kanban column not shown in Gantt Chart

### ISSUE THREAD

**Issue by javascript-programming** [bryntum/odoo-support#5]
![Screenshot 2021-05-17 at 14 27 24](https://user-images.githubusercontent.com/25703411/118488546-2143f080-b71c-11eb-8739-5251c11bd39a.png)

**Comment by christos-ts** [comment]
Any update on this bug ?

**Comment by javascript-programming** [comment]
This one is scheduled for the upcoming release.

**Comment by HosniD** [comment]
resolved
