### ISSUE TITLE
Impossible to change task name

### ISSUE THREAD

**Issue by grzekru** [bryntum/odoo-support#9]
1. https://odoo-gantt.bryntum.com/web#action=164&model=project.project&view_type=kanban&cids=1&menu_id=102
2. Projekt 1
3. Gantt view
4. Try to change name of "task1"

**Comment by javascript-programming** [comment]
Bug saving task name on tasks without dates is resolved. 

Saving project name remains
https://github.com/bryntum/odoo-support/issues/11
